/**
 * Model Stack API
 * Serves the model-stack-data.json generated by the openrouter-rankings script
 */
import { NextResponse } from 'next/server';
import { readFile } from 'fs/promises';
import { join } from 'path';

const STACK_DATA_PATH = process.env.MODEL_STACK_DATA_PATH
  ?? join(process.env.HOME ?? '/root', '.openclaw', 'workspace', 'memory', 'model-stack-data.json');

export async function GET() {
  try {
    const raw = await readFile(STACK_DATA_PATH, 'utf-8');
    const data = JSON.parse(raw);
    return NextResponse.json(data);
  } catch {
    return NextResponse.json({ error: 'Stack data not available' }, { status: 404 });
  }
}
