server {
  listen 80;
  listen [::]:80;
  server_name pearlos.org www.pearlos.org;

  root /var/www/pearlos-website;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /pearl-website {
    alias /var/www/pearlos-website;
    index index.html;
    try_files $uri $uri/ /pearl-website/index.html;
  }

  location /assets/ {
    alias /var/www/pearlos-website/assets/;
  }
}
