/**
 * Agency Coordinator for PearlOS Kitchen Experience
 *
 * Detects creation intent, routes to design-doc or direct-build,
 * generates design documents, and spawns Agency build swarms.
 */

// --- Types ---

interface CreationIntent {
  detected: boolean;
  type: 'game' | 'app' | 'feature' | 'presentation' | 'unknown';
  confidence: number;
}

interface UserHistory {
  projectCount: number;
  recentProjects: { type: string; complexity: string }[];
}

interface RouteDecision {
  route: 'design-doc' | 'direct-build';
}

interface SwarmResult {
  swarmId: string;
  leadTaskId: string;
  workerTaskIds: {
    design: string;
    code: string;
    art: string;
    qa: string;
  };
}

// --- Constants ---

const CREATION_KEYWORDS = ['make', 'build', 'create', 'design'] as const;

const TYPE_SIGNALS: Record<string, string[]> = {
  game: ['game', 'play', 'level', 'score', 'player', 'enemy', 'platformer', 'rpg', 'puzzle'],
  app: ['app', 'application', 'tool', 'utility', 'dashboard', 'tracker'],
  feature: ['feature', 'add', 'integrate', 'plugin', 'module', 'extension'],
  presentation: ['presentation', 'slides', 'deck', 'pitch', 'demo', 'showcase'],
};

const COMPLEXITY_THRESHOLD = 3;

// --- Function 1: detectCreationIntent ---

export function detectCreationIntent(message: string): CreationIntent {
  const lower = message.toLowerCase();
  const words = lower.split(/\s+/);

  const hasCreationKeyword = CREATION_KEYWORDS.some((kw) => words.includes(kw));

  if (!hasCreationKeyword) {
    return { detected: false, type: 'unknown', confidence: 0 };
  }

  let bestType: CreationIntent['type'] = 'unknown';
  let bestScore = 0;

  for (const [type, signals] of Object.entries(TYPE_SIGNALS)) {
    const matchCount = signals.filter((s) => lower.includes(s)).length;
    if (matchCount > bestScore) {
      bestScore = matchCount;
      bestType = type as CreationIntent['type'];
    }
  }

  // Confidence: base 0.5 for keyword match, +0.1 per type signal, cap at 1.0
  const confidence = Math.min(1.0, 0.5 + bestScore * 0.1);

  return { detected: true, type: bestType, confidence };
}

// --- Function 2: offerDesignDocOrDirectBuild ---

export function offerDesignDocOrDirectBuild(
  intent: CreationIntent,
  userHistory: UserHistory
): RouteDecision {
  const isReturningUser = userHistory.projectCount > 0;
  const isSimpleType = intent.type === 'feature' || intent.type === 'presentation';
  const isHighConfidence = intent.confidence >= 0.8;

  // Returning users with simple/clear intent → direct build
  if (isReturningUser && (isSimpleType || isHighConfidence)) {
    return { route: 'direct-build' };
  }

  // New users or complex projects → suggest design doc
  const hasComplexHistory = userHistory.recentProjects.some((p) => p.complexity === 'high');
  if (!isReturningUser || intent.type === 'game' || hasComplexHistory) {
    return { route: 'design-doc' };
  }

  // Default: projects with moderate complexity get a design doc
  if (intent.confidence < 0.7) {
    return { route: 'design-doc' };
  }

  return { route: 'direct-build' };
}

// --- Function 3: generateDesignDocDraft ---

export async function generateDesignDocDraft(intent: CreationIntent): Promise<string> {
  const typeLabel = intent.type === 'unknown' ? 'Project' : intent.type;
  const title = `${typeLabel.charAt(0).toUpperCase() + typeLabel.slice(1)} Design Document`;

  // Template-based draft; in production, augment with LLM call
  const markdown = `# ${title}

## Vision
<!-- Describe what this ${typeLabel} will do and why it matters -->

## Core Mechanics
<!-- Key interactions, rules, or workflows -->
-

## Tech Stack
<!-- Recommended technologies and frameworks -->
- **Frontend:** React / Next.js
- **Backend:** Node.js
- **Storage:** Prism data layer

## Milestones

### Phase 1: Foundation
- [ ] Project scaffolding
- [ ] Core data models
- [ ] Basic UI shell

### Phase 2: Core Features
- [ ] Primary ${typeLabel} logic
- [ ] User interactions
- [ ] State management

### Phase 3: Polish & QA
- [ ] Visual polish
- [ ] Testing coverage
- [ ] Performance optimization

### Phase 4: Launch
- [ ] Final QA pass
- [ ] Deployment
- [ ] User feedback loop

---
*Generated by Agency Coordinator — PearlOS Kitchen*
`;

  return markdown;
}

// --- Function 4: spawnAgencyBuild ---

let swarmCounter = 0;

function generateId(prefix: string): string {
  swarmCounter++;
  return `${prefix}-${Date.now()}-${swarmCounter}`;
}

export async function spawnAgencyBuild(
  projectId: string,
  designDoc: string,
  launchpadProjectId: string
): Promise<SwarmResult> {
  const swarmId = generateId('swarm');
  const leadTaskId = generateId('lead');

  // Lead Agent: decompose design doc into worker tasks
  const workerTaskIds = {
    design: generateId('worker-design'),
    code: generateId('worker-code'),
    art: generateId('worker-art'),
    qa: generateId('worker-qa'),
  };

  // Register swarm in TaskBar tracking
  const swarmManifest = {
    swarmId,
    projectId,
    launchpadProjectId,
    leadTaskId,
    workers: workerTaskIds,
    designDoc: designDoc.slice(0, 200) + '...', // summary for tracking
    status: 'spawned',
    createdAt: new Date().toISOString(),
  };

  // In production: persist swarmManifest, dispatch worker tasks to queue
  console.log(`[Agency] Swarm ${swarmId} spawned for project ${projectId}`);
  console.log(`[Agency] Lead: ${leadTaskId}`);
  console.log(`[Agency] Workers: Design(${workerTaskIds.design}), Code(${workerTaskIds.code}), Art(${workerTaskIds.art}), QA(${workerTaskIds.qa})`);
  console.log(`[Agency] Tracking in Launchpad: ${launchpadProjectId}`);

  return { swarmId, leadTaskId, workerTaskIds };
}
