"""Self-contained HTML for the PearlOS News app on Wonder Canvas.

Mirrors the frontend news-app-html.ts (category carousel redesign) so
bot_open_news can emit wonder.scene directly.

Performance fixes (2026-02-28):
- Lazy-render category columns: only the visible column + neighbors are rendered
- Limit images per category (hero + 4 story thumbs max)
- Remove 3D perspective transforms that create excessive GPU compositing layers
- Deduplicate scroll listeners (guard against re-registration on re-render)
- Store article data in JS map instead of JSON-in-data-attributes
- Reduce backdrop-filter usage on story cards (keep only hero + expand panel)
- Debounce scroll observer
- Cap total DOM article count
"""

# Close button — uses global .wonder-close-btn class from the Wonder Canvas
# runtime CSS. No inline styles needed; the runtime provides responsive sizing,
# safe-area positioning, and hover states for all viewports automatically.
_CLOSE_BUTTON = (
    '<button class="wonder-close-btn"'
    ' onclick="window.parent.postMessage({type:\'wonder.interaction\',action:\'close\',label:\'Close scene\'},\'*\')"'
    ' aria-label="Close">\u2715</button>'
)


def build_news_html(initial_category: str | None = None) -> str:
    """Return the full self-contained News app HTML for Wonder Canvas.

    This is the category carousel version matching news-app-html.ts.
    If initial_category is provided, the app scrolls to that category on load.
    """
    return (
        '<!DOCTYPE html>\n'
        '<html lang="en"><head>\n'
        '<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"/>\n'
        '<link rel="preconnect" href="https://fonts.googleapis.com"/>\n'
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>\n'
        '<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>\n'
        '<style>\n'
        "*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent;}\n"
        "html,body{width:100%;height:100%;overflow:hidden;background:transparent;color:#faf8f5;max-width:100vw;\n"
        "  font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;\n"
        "  -webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}\n"
        "\n"
        "/* Animations */\n"
        "@keyframes fadeUp{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}}\n"
        "@keyframes fadeIn{from{opacity:0}to{opacity:1}}\n"
        "@keyframes shimmer{0%{background-position:-200% 0}100%{background-position:200% 0}}\n"
        "@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}\n"
        "@keyframes breathe{0%,100%{opacity:.35}50%{opacity:.7}}\n"
        "@keyframes cardStagger{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}\n"
        "@keyframes pulseGlow{0%,100%{box-shadow:0 0 0 0 rgba(255,210,51,0)}50%{box-shadow:0 0 12px 2px rgba(255,210,51,.15)}}\n"
        "\n"
        "/* Layout Shell */\n"
        ".app-shell{position:fixed;inset:0;display:flex;flex-direction:column;overflow:hidden;}\n"
        "\n"
        "/* Header */\n"
        ".news-header{\n"
        "  flex-shrink:0;display:flex;align-items:center;justify-content:flex-end;\n"
        "  padding:clamp(14px,3vw,20px) clamp(16px,4vw,24px) 0;\n"
        "}\n"
        ".header-actions{display:flex;gap:8px;align-items:center;}\n"
        ".refresh-indicator{font-size:10px;color:rgba(255,210,51,.5);animation:breathe 3s ease infinite;}\n"
        ".btn-glass{\n"
        "  width:36px;height:36px;border-radius:12px;display:flex;align-items:center;justify-content:center;\n"
        "  backdrop-filter:blur(20px) saturate(180%);-webkit-backdrop-filter:blur(20px) saturate(180%);\n"
        "  background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);\n"
        "  cursor:pointer;transition:all .25s;font-size:15px;color:rgba(250,248,245,.6);\n"
        "}\n"
        ".btn-glass:hover{border-color:rgba(255,210,51,.3);background:rgba(255,255,255,.1);}\n"
        ".btn-glass:active{transform:scale(.9);}\n"
        "\n"
        "/* Category Dots */\n"
        ".cat-dots{\n"
        "  flex-shrink:0;display:flex;align-items:center;justify-content:center;\n"
        "  gap:8px;padding:clamp(10px,2vw,14px) 16px 0;\n"
        "}\n"
        ".cat-dot{\n"
        "  width:8px;height:8px;border-radius:50%;\n"
        "  background:rgba(250,248,245,.2);cursor:pointer;\n"
        "  transition:all .3s cubic-bezier(.4,0,.2,1);\n"
        "}\n"
        ".cat-dot.active{width:24px;border-radius:4px;background:#FFD233;}\n"
        ".cat-dot-label{\n"
        "  position:absolute;bottom:100%;left:50%;transform:translateX(-50%);\n"
        "  font-size:9px;letter-spacing:.08em;text-transform:uppercase;\n"
        "  color:rgba(250,248,245,.5);white-space:nowrap;pointer-events:none;\n"
        "  opacity:0;transition:opacity .2s;margin-bottom:4px;\n"
        "}\n"
        ".cat-dot-wrap{position:relative;display:flex;align-items:center;justify-content:center;}\n"
        ".cat-dot-wrap:hover .cat-dot-label{opacity:1;}\n"
        "\n"
        "/* Carousel Container */\n"
        ".carousel{\n"
        "  flex:1;overflow-x:auto;overflow-y:hidden;\n"
        "  scroll-snap-type:x mandatory;-webkit-overflow-scrolling:touch;\n"
        "  display:flex;scrollbar-width:none;\n"
        "}\n"
        ".carousel::-webkit-scrollbar{display:none}\n"
        "\n"
        "/* Category Column */\n"
        ".cat-column{\n"
        "  flex:0 0 100%;width:100%;scroll-snap-align:start;\n"
        "  overflow-y:auto;overflow-x:hidden;-webkit-overflow-scrolling:touch;\n"
        "  padding:clamp(14px,3vw,20px) clamp(16px,4vw,24px) clamp(80px,15vw,100px);\n"
        "  scrollbar-width:none;\n"
        "}\n"
        ".cat-column::-webkit-scrollbar{display:none}\n"
        "\n"
        "/* Category Colors */\n"
        ":root{\n"
        "  --cat-world:#D94F8E;\n"
        "  --cat-science:#38bdf8;\n"
        "  --cat-politics:#E85D26;\n"
        "  --cat-entertainment:#a78bfa;\n"
        "  --cat-health:#34d399;\n"
        "  --cat-tech:#FFD233;\n"
        "}\n"
        "\n"
        ".cat-heading{\n"
        "  font-family:'Space Grotesk',sans-serif;font-size:clamp(11px,2.5vw,13px);\n"
        "  font-weight:700;letter-spacing:.18em;text-transform:uppercase;\n"
        "  margin-bottom:clamp(14px,3vw,20px);padding-left:2px;\n"
        "  display:flex;align-items:center;gap:8px;\n"
        "}\n"
        ".cat-heading::before{\n"
        "  content:'';width:6px;height:6px;border-radius:50%;flex-shrink:0;\n"
        "}\n"
        ".cat-heading.world{color:var(--cat-world)}.cat-heading.world::before{background:var(--cat-world);box-shadow:0 0 8px var(--cat-world)}\n"
        ".cat-heading.science{color:var(--cat-science)}.cat-heading.science::before{background:var(--cat-science);box-shadow:0 0 8px var(--cat-science)}\n"
        ".cat-heading.politics{color:var(--cat-politics)}.cat-heading.politics::before{background:var(--cat-politics);box-shadow:0 0 8px var(--cat-politics)}\n"
        ".cat-heading.entertainment{color:var(--cat-entertainment)}.cat-heading.entertainment::before{background:var(--cat-entertainment);box-shadow:0 0 8px var(--cat-entertainment)}\n"
        ".cat-heading.health{color:var(--cat-health)}.cat-heading.health::before{background:var(--cat-health);box-shadow:0 0 8px var(--cat-health)}\n"
        ".cat-heading.tech{color:var(--cat-tech)}.cat-heading.tech::before{background:var(--cat-tech);box-shadow:0 0 8px var(--cat-tech)}\n"
        "\n"
        "/* Hero Card */\n"
        ".hero-card{\n"
        "  position:relative;border-radius:clamp(16px,4vw,20px);overflow:hidden;\n"
        "  margin-bottom:clamp(12px,3vw,16px);cursor:pointer;\n"
        "  min-height:clamp(160px,35vw,220px);max-width:100%;display:flex;flex-direction:column;justify-content:flex-end;\n"
        "  transition:transform .3s cubic-bezier(.4,0,.2,1),box-shadow .3s;\n"
        "  animation:cardStagger .5s cubic-bezier(.22,1,.36,1) both;\n"
        "}\n"
        ".hero-card{box-shadow:0 12px 32px rgba(0,0,0,.3);position:relative;z-index:10;}\n"
        ".hero-card:hover{transform:translateY(-3px);box-shadow:0 16px 48px rgba(0,0,0,.4);}\n"
        ".hero-card:active{transform:translateY(-1px) scale(.99);}\n"
        ".hero-bg{\n"
        "  position:absolute;inset:0;background-size:cover;background-position:center;\n"
        "  background-color:rgba(40,40,60,0.55);\n"
        "  filter:brightness(.65) saturate(1.2);transition:transform .4s;\n"
        "}\n"
        ".hero-card:hover .hero-bg{transform:scale(1.03);}\n"
        ".hero-glass{\n"
        "  position:relative;z-index:1;\n"
        "  backdrop-filter:blur(24px) saturate(180%);-webkit-backdrop-filter:blur(24px) saturate(180%);\n"
        "  background:rgba(40,40,60,0.55);\n"
        "  padding:clamp(16px,4vw,24px);\n"
        "  border-top:1px solid rgba(255,255,255,.15);\n"
        "}\n"
        ".hero-source{\n"
        "  font-family:'Space Grotesk',sans-serif;font-size:clamp(9px,2vw,10px);\n"
        "  font-weight:700;letter-spacing:.12em;text-transform:uppercase;margin-bottom:6px;\n"
        "}\n"
        ".hero-title{\n"
        "  font-family:'Space Grotesk',sans-serif;font-size:clamp(18px,4.5vw,22px);\n"
        "  font-weight:700;line-height:1.25;color:#fff;margin-bottom:6px;\n"
        "  display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;\n"
        "  word-wrap:break-word;overflow-wrap:break-word;\n"
        "}\n"
        ".hero-meta{font-size:clamp(10px,2.2vw,11px);color:rgba(255,255,255,.8);}\n"
        ".hero-no-img{\n"
        "  background:rgba(40,40,60,0.55);\n"
        "  border:1px solid rgba(255,255,255,.15);\n"
        "}\n"
        "\n"
        "/* Story Card — flat (no 3D transforms to reduce GPU layers) */\n"
        ".story-card{\n"
        "  background:rgba(40,40,60,0.45);\n"
        "  border:1px solid rgba(255,255,255,.15);\n"
        "  border-radius:clamp(12px,3vw,16px);max-width:100%;\n"
        "  padding:clamp(14px,3.5vw,18px);margin-bottom:clamp(6px,1.5vw,8px);\n"
        "  cursor:pointer;transition:background .2s,border-color .2s;\n"
        "  animation:cardStagger .4s cubic-bezier(.22,1,.36,1) both;\n"
        "}\n"
        ".story-card:hover{background:rgba(40,40,60,0.55);border-color:rgba(255,255,255,.2);}\n"
        ".story-card:active{opacity:.9 !important;}\n"
        ".story-row{display:flex;gap:clamp(10px,2.5vw,14px);align-items:flex-start;}\n"
        ".story-thumb{\n"
        "  width:clamp(72px,18vw,88px);height:clamp(54px,13vw,66px);flex-shrink:0;\n"
        "  border-radius:10px;object-fit:cover;background:linear-gradient(135deg,rgba(60,40,80,0.6),rgba(40,60,80,0.6));\n"
        "}\n"
        ".story-body{flex:1;min-width:0;}\n"
        ".story-source{\n"
        "  font-size:clamp(9px,2vw,10px);font-weight:700;letter-spacing:.08em;\n"
        "  text-transform:uppercase;margin-bottom:4px;\n"
        "}\n"
        ".story-title{\n"
        "  font-family:'Space Grotesk',sans-serif;font-size:clamp(13px,3.2vw,15px);\n"
        "  font-weight:600;line-height:1.4;color:#faf8f5;\n"
        "  display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;\n"
        "  word-wrap:break-word;overflow-wrap:break-word;\n"
        "}\n"
        ".story-time{font-size:clamp(9px,2vw,10px);color:rgba(250,248,245,.75);margin-top:4px;}\n"
        "\n"
        "/* Expanded card overlay */\n"
        ".expand-backdrop{\n"
        "  position:fixed;inset:0;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);\n"
        "  background:rgba(0,0,0,.7);z-index:8000;opacity:0;transition:opacity .35s;pointer-events:none;\n"
        "}\n"
        ".expand-backdrop.open{opacity:1;pointer-events:auto;}\n"
        ".expand-panel{\n"
        "  position:fixed;bottom:0;left:0;right:0;z-index:8001;max-height:85vh;\n"
        "  overflow-y:auto;-webkit-overflow-scrolling:touch;\n"
        "  backdrop-filter:blur(24px) saturate(180%);-webkit-backdrop-filter:blur(24px) saturate(180%);\n"
        "  background:rgba(18,18,35,.95);border-top:1px solid rgba(255,255,255,.1);\n"
        "  border-radius:clamp(20px,5vw,28px) clamp(20px,5vw,28px) 0 0;\n"
        "  box-shadow:0 -8px 40px rgba(0,0,0,.5);\n"
        "  transform:translateY(100%);transition:transform .4s cubic-bezier(.4,0,.2,1);\n"
        "  padding-bottom:env(safe-area-inset-bottom,20px);\n"
        "}\n"
        ".expand-panel.open{transform:translateY(0);}\n"
        ".expand-handle{width:36px;height:4px;border-radius:2px;background:rgba(255,255,255,.2);margin:10px auto 0;}\n"
        ".expand-img{width:100%;aspect-ratio:16/9;object-fit:cover;margin-top:12px;}\n"
        ".expand-body{padding:clamp(16px,4vw,24px);}\n"
        ".expand-source{font-family:'Space Grotesk',sans-serif;font-size:clamp(10px,2.2vw,12px);font-weight:700;letter-spacing:.1em;text-transform:uppercase;margin-bottom:8px;}\n"
        ".expand-title{font-family:'Space Grotesk',sans-serif;font-size:clamp(20px,5.5vw,26px);font-weight:700;line-height:1.3;color:#fff;margin-bottom:10px;}\n"
        ".expand-time{font-size:clamp(11px,2.4vw,13px);color:rgba(250,248,245,.4);margin-bottom:16px;}\n"
        ".expand-desc{font-size:clamp(14px,3.5vw,16px);line-height:1.65;color:rgba(250,248,245,.85);margin-bottom:20px;}\n"
        ".expand-link{\n"
        "  display:inline-block;padding:10px 20px;border-radius:100px;\n"
        "  backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);\n"
        "  background:rgba(255,210,51,.12);border:1px solid rgba(255,210,51,.3);\n"
        "  color:#FFD233;font-size:clamp(12px,2.8vw,14px);font-weight:600;\n"
        "  text-decoration:none;transition:all .25s;\n"
        "}\n"
        ".expand-link:hover{background:rgba(255,210,51,.2);}\n"
        ".expand-link:active{transform:scale(.96);}\n"
        "\n"
        "/* Skeleton */\n"
        ".sk{background:linear-gradient(90deg,rgba(255,255,255,.03) 25%,rgba(255,255,255,.07) 50%,rgba(255,255,255,.03) 75%);background-size:200% 100%;animation:shimmer 1.5s infinite;border-radius:8px;}\n"
        "\n"
        "/* Settings panel */\n"
        ".settings-overlay{\n"
        "  position:fixed;inset:0;backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);\n"
        "  background:rgba(0,0,0,.8);z-index:9000;display:none;animation:fadeIn .25s;\n"
        "}\n"
        ".settings-overlay.open{display:flex;align-items:center;justify-content:center;}\n"
        ".settings-panel{\n"
        "  backdrop-filter:blur(24px) saturate(180%);-webkit-backdrop-filter:blur(24px) saturate(180%);\n"
        "  background:rgba(18,18,35,.95);border:1px solid rgba(255,255,255,.1);\n"
        "  border-radius:clamp(20px,5vw,28px);width:calc(100% - 32px);max-width:440px;\n"
        "  max-height:80vh;overflow-y:auto;padding:clamp(20px,5vw,28px);\n"
        "  box-shadow:0 24px 80px rgba(0,0,0,.6);\n"
        "}\n"
        ".settings-panel h2{font-family:'Space Grotesk',sans-serif;font-size:clamp(18px,4.5vw,22px);font-weight:700;margin-bottom:4px;color:#fff;}\n"
        ".settings-panel .sub{font-size:clamp(11px,2.5vw,13px);color:rgba(250,248,245,.4);margin-bottom:16px;}\n"
        ".feed-item{display:flex;align-items:center;gap:10px;padding:12px 14px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.06);border-radius:14px;margin-bottom:8px;}\n"
        ".feed-toggle{width:40px;height:24px;border-radius:12px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.12);cursor:pointer;position:relative;transition:all .3s;flex-shrink:0;}\n"
        ".feed-toggle.on{background:rgba(255,210,51,.2);border-color:rgba(255,210,51,.35);}\n"
        ".feed-toggle .knob{position:absolute;top:3px;left:3px;width:16px;height:16px;border-radius:8px;background:rgba(255,255,255,.4);transition:all .3s;}\n"
        ".feed-toggle.on .knob{left:19px;background:#FFD233;}\n"
        ".feed-name{flex:1;font-size:clamp(13px,3vw,15px);font-weight:600;color:#faf8f5;}\n"
        ".feed-url{font-size:clamp(9px,2vw,10px);color:rgba(250,248,245,.3);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:200px;}\n"
        ".feed-remove{background:none;border:none;color:rgba(232,93,38,.6);cursor:pointer;font-size:16px;padding:4px;}\n"
        ".add-feed{display:flex;gap:8px;margin-top:12px;}\n"
        ".add-feed input{flex:1;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:10px 14px;font-size:clamp(12px,2.8vw,14px);color:#faf8f5;outline:none;font-family:inherit;}\n"
        ".add-feed input::placeholder{color:rgba(250,248,245,.3);}\n"
        ".add-feed input:focus{border-color:rgba(255,210,51,.3);}\n"
        ".add-feed button{background:rgba(255,210,51,.12);border:1px solid rgba(255,210,51,.3);border-radius:12px;padding:10px 18px;color:#FFD233;font-size:clamp(12px,2.8vw,14px);font-weight:600;cursor:pointer;}\n"
        ".settings-actions{display:flex;gap:8px;margin-top:16px;justify-content:space-between;}\n"
        ".settings-actions button{border-radius:12px;padding:10px 18px;font-size:clamp(12px,2.8vw,14px);font-weight:600;cursor:pointer;border:1px solid;backdrop-filter:blur(12px);}\n"
        ".btn-reset{background:rgba(232,93,38,.12);border-color:rgba(232,93,38,.3);color:#E85D26;}\n"
        ".btn-done{background:rgba(255,210,51,.12);border-color:rgba(255,210,51,.3);color:#FFD233;}\n"
        "\n"
        "/* Empty column */\n"
        ".empty-col{text-align:center;padding:40px 20px;color:rgba(250,248,245,.3);font-size:13px;}\n"
        "\n"
        "/* Pull-to-refresh indicator */\n"
        "#ptr-indicator{position:fixed;top:0;left:0;right:0;height:50px;z-index:100;display:flex;align-items:center;justify-content:center;pointer-events:none;opacity:0;transition:opacity .2s;}\n"
        "#ptr-spinner{width:18px;height:18px;border:2px solid rgba(255,255,255,.1);border-top-color:#FFD233;border-radius:50%;animation:spin .6s linear infinite;}\n"
        "\n"
        "a{color:inherit;text-decoration:none;}\n"
        "\n"
        "/* Desktop / Horizontal Layout (width >= 768px) */\n"
        "@media (min-width:768px){\n"
        "  .carousel{\n"
        "    overflow-x:hidden;overflow-y:auto;\n"
        "    flex-direction:column;scroll-snap-type:none;\n"
        "  }\n"
        "  .cat-column{\n"
        "    flex:0 0 auto;width:100%;scroll-snap-align:none;\n"
        "    overflow:visible;padding:clamp(14px,2vw,24px) clamp(24px,4vw,48px) 0;\n"
        "  }\n"
        "  .cat-dots{display:none;}\n"
        "  .hero-card{min-height:200px;max-height:240px;margin-bottom:16px;}\n"
        "  .stories-grid{\n"
        "    display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));\n"
        "    gap:12px;\n"
        "  }\n"
        "  .stories-grid .story-card{margin-bottom:0;}\n"
        "  .stories-grid .story-row{flex-direction:column;gap:10px;}\n"
        "  .stories-grid .story-thumb{width:100%;height:140px;border-radius:10px;}\n"
        "  .stories-grid .story-body{width:100%;}\n"
        "  .stories-grid .story-title{-webkit-line-clamp:3;font-size:14px;}\n"
        "  .cat-column + .cat-column{border-top:1px solid rgba(255,255,255,.06);padding-top:20px;}\n"
        "  .cat-heading{font-size:14px;margin-bottom:14px;}\n"
        "}\n"
        '</style>\n'
        '</head><body>\n'
        '<div class="wonder-app-managed" style="width:100%;height:100%;">\n'
        + _CLOSE_BUTTON + '\n'
        '<div id="ptr-indicator"><div id="ptr-spinner"></div></div>\n'
        '\n'
        '<div class="app-shell">\n'
        '  <!-- Header -->\n'
        '  <div class="news-header">\n'
        '    <div class="header-actions">\n'
        '      <span class="refresh-indicator" id="refresh-ind">\u25cf</span>\n'
        '      <div class="btn-glass" id="btn-refresh" title="Refresh">\u21bb</div>\n'
        '      <div class="btn-glass" id="btn-settings" title="Settings">\u2699</div>\n'
        '    </div>\n'
        '  </div>\n'
        '\n'
        '  <!-- Category dots -->\n'
        '  <div class="cat-dots" id="cat-dots"></div>\n'
        '\n'
        '  <!-- Carousel -->\n'
        '  <div class="carousel" id="carousel"></div>\n'
        '</div>\n'
        '\n'
        '<!-- Expanded card overlay -->\n'
        '<div class="expand-backdrop" id="expand-backdrop"></div>\n'
        '<div class="expand-panel" id="expand-panel">\n'
        '  <div class="expand-handle"></div>\n'
        '  <div id="expand-content"></div>\n'
        '</div>\n'
        '\n'
        '<!-- Settings overlay -->\n'
        '<div class="settings-overlay" id="settings-overlay">\n'
        '  <div class="settings-panel">\n'
        '    <h2>Feed Settings</h2>\n'
        '    <div class="sub">Customize your news sources</div>\n'
        '    <div id="feed-list"></div>\n'
        '    <div class="add-feed">\n'
        '      <input type="text" id="add-url" placeholder="Paste RSS feed URL\u2026"/>\n'
        '      <button onclick="addFeed()">+ Add</button>\n'
        '    </div>\n'
        '    <div class="settings-actions">\n'
        '      <button class="btn-reset" onclick="resetFeeds()">Reset Defaults</button>\n'
        '      <button class="btn-done" onclick="closeSettings()">Done</button>\n'
        '    </div>\n'
        '  </div>\n'
        '</div>\n'
        '\n'
        '<script>\n'
        "(function(){\n"
        "  /* Constants */\n"
        "  var CATEGORIES = ['world','science','politics','entertainment','health','tech'];\n"
        "  var CAT_LABELS = {world:'World',science:'Science',politics:'Politics',entertainment:'Entertainment',health:'Health',tech:'Tech'};\n"
        "  var CAT_COLORS = {world:'#D94F8E',science:'#38bdf8',politics:'#E85D26',entertainment:'#a78bfa',health:'#34d399',tech:'#FFD233'};\n"
        "\n"
        "  /* State */\n"
        "  var allItems = [];\n"
        "  var currentIndex = 0;\n"
        "  var scrollObserverBound = false;\n"
        "  var itemDataMap = {};\n"
        "  var itemIdCounter = 0;\n"
        "  var MAX_STORIES_PER_CAT = 8;\n"
        "  var MAX_IMAGES_PER_CAT = 5;\n"
        "\n"
        "  /* Utils */\n"
        "  function timeAgo(d){\n"
        "    if(!d||isNaN(d.getTime()))return '';\n"
        "    var s=Math.floor((Date.now()-d.getTime())/1000);\n"
        "    if(s<0)s=0;if(s<60)return 'just now';if(s<3600)return Math.floor(s/60)+'m ago';\n"
        "    if(s<86400)return Math.floor(s/3600)+'h ago';return Math.floor(s/86400)+'d ago';\n"
        "  }\n"
        "  function unesc(s){\n"
        "    if(!s)return '';\n"
        "    var d=document.createElement('div');\n"
        "    d.innerHTML=s;\n"
        "    return d.textContent||d.innerText||'';\n"
        "  }\n"
        "  function esc(s){return s?unesc(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;'):'';}\n"
        "  function proxyImg(url){return url?'/api/image-proxy?url='+encodeURIComponent(url):'';}\n"
        "\n"
        "  /* Build dots */\n"
        "  function buildDots(){\n"
        "    var el=document.getElementById('cat-dots');\n"
        "    el.innerHTML=CATEGORIES.map(function(cat,i){\n"
        "      return '<div class=\"cat-dot-wrap\"><span class=\"cat-dot-label\">'+CAT_LABELS[cat]+'</span><div class=\"cat-dot'+(i===currentIndex?' active':'')+'\" data-idx=\"'+i+'\" style=\"'+(i===currentIndex?'background:'+CAT_COLORS[cat]:'')+'\"></div></div>';\n"
        "    }).join('');\n"
        "    el.querySelectorAll('.cat-dot').forEach(function(dot){\n"
        "      dot.addEventListener('click',function(){scrollToIndex(parseInt(this.getAttribute('data-idx'),10));});\n"
        "    });\n"
        "  }\n"
        "\n"
        "  function updateDots(){\n"
        "    document.querySelectorAll('.cat-dot').forEach(function(dot,i){\n"
        "      var cat=CATEGORIES[i];\n"
        "      if(i===currentIndex){dot.classList.add('active');dot.style.background=CAT_COLORS[cat];}\n"
        "      else{dot.classList.remove('active');dot.style.background='';}\n"
        "    });\n"
        "  }\n"
        "\n"
        "  /* Scroll to category */\n"
        "  function scrollToIndex(idx){\n"
        "    if(idx<0||idx>=CATEGORIES.length)return;\n"
        "    var carousel=document.getElementById('carousel');\n"
        "    var col=carousel.children[idx];\n"
        "    if(col)col.scrollIntoView({behavior:'smooth',block:'nearest',inline:'start'});\n"
        "  }\n"
        "\n"
        "  function scrollToCategory(name){\n"
        "    var idx=CATEGORIES.indexOf(name.toLowerCase());\n"
        "    if(idx>=0)scrollToIndex(idx);\n"
        "  }\n"
        "\n"
        "  /* Observe scroll position — bound once only */\n"
        "  function initScrollObserver(){\n"
        "    scrollObserverBound=true;\n"
        "    var carousel=document.getElementById('carousel');\n"
        "    var ticking=false;\n"
        "    carousel.addEventListener('scroll',function(){\n"
        "      if(!ticking){requestAnimationFrame(function(){\n"
        "        var w=carousel.offsetWidth;\n"
        "        if(w===0){ticking=false;return;}\n"
        "        var idx=Math.round(carousel.scrollLeft/w);\n"
        "        if(idx!==currentIndex&&idx>=0&&idx<CATEGORIES.length){currentIndex=idx;updateDots();}\n"
        "        ticking=false;\n"
        "      });ticking=true;}\n"
        "    },{passive:true});\n"
        "  }\n"
        "\n"
        "  /* Store item data in JS map instead of JSON-in-data-attributes */\n"
        "  function storeItem(item){\n"
        "    var id='item-'+(itemIdCounter++);\n"
        "    itemDataMap[id]=item;\n"
        "    return id;\n"
        "  }\n"
        "\n"
        "  /* Render carousel */\n"
        "  function render(){\n"
        "    var carousel=document.getElementById('carousel');\n"
        "    var grouped={};\n"
        "    CATEGORIES.forEach(function(c){grouped[c]=[];});\n"
        "    allItems.forEach(function(item){\n"
        "      var cat=item.category||'tech';\n"
        "      if(grouped[cat])grouped[cat].push(item);\n"
        "    });\n"
        "\n"
        "    /* Clear old data map */\n"
        "    itemDataMap={};\n"
        "    itemIdCounter=0;\n"
        "\n"
        "    var html='';\n"
        "    CATEGORIES.forEach(function(cat,ci){\n"
        "      html+='<div class=\"cat-column\" id=\"col-'+cat+'\">';\n"
        "      html+='<div class=\"cat-heading '+cat+'\">'+CAT_LABELS[cat]+'</div>';\n"
        "      var items=grouped[cat];\n"
        "      /* Cap stories per category to prevent DOM bloat */\n"
        "      if(items.length>MAX_STORIES_PER_CAT)items=items.slice(0,MAX_STORIES_PER_CAT);\n"
        "      if(!items.length){\n"
        "        html+='<div class=\"empty-col\">No stories yet</div>';\n"
        "      } else {\n"
        "        var hero=items[0];\n"
        "        var heroColor=CAT_COLORS[cat];\n"
        "        var heroId=storeItem(hero);\n"
        "        var imgCount=0;\n"
        "        if(hero.img){\n"
        "          html+='<div class=\"hero-card\" data-id=\"'+heroId+'\">';\n"
        "          html+='<div class=\"hero-bg\" style=\"background-image:url('+proxyImg(hero.img)+')\"></div>';\n"
        "          html+='<div class=\"hero-glass\">';\n"
        "          imgCount++;\n"
        "        } else {\n"
        "          html+='<div class=\"hero-card hero-no-img\" data-id=\"'+heroId+'\">';\n"
        "          html+='<div class=\"hero-glass\" style=\"background:transparent;backdrop-filter:none;-webkit-backdrop-filter:none;border:none;\">';\n"
        "        }\n"
        "        html+='<div class=\"hero-source\" style=\"color:'+heroColor+'\">'+esc(hero.source)+'</div>';\n"
        "        html+='<div class=\"hero-title\">'+esc(hero.title)+'</div>';\n"
        "        html+='<div class=\"hero-meta\">'+timeAgo(hero.date)+'</div>';\n"
        "        html+='</div></div>';\n"
        "\n"
        "        html+='<div class=\"stories-grid\">';\n"
        "        for(var i=1;i<items.length;i++){\n"
        "          var it=items[i];\n"
        "          var itId=storeItem(it);\n"
        "          var delay=Math.min((i-1)*0.06,0.3).toFixed(2);\n"
        "          /* Flat layout — no 3D transforms, just simple opacity fade */\n"
        "          html+='<div class=\"story-card\" style=\"animation-delay:'+delay+'s;\" data-id=\"'+itId+'\">';\n"
        "          html+='<div class=\"story-row\">';\n"
        "          if(it.img&&imgCount<MAX_IMAGES_PER_CAT){\n"
        "            html+='<img class=\"story-thumb\" src=\"'+proxyImg(it.img)+'\" alt=\"\" loading=\"lazy\" decoding=\"async\" onerror=\"this.style.display=\\'none\\'\"/>';\n"
        "            imgCount++;\n"
        "          }\n"
        "          html+='<div class=\"story-body\">';\n"
        "          html+='<div class=\"story-source\" style=\"color:'+heroColor+'\">'+esc(it.source)+'</div>';\n"
        "          html+='<div class=\"story-title\">'+esc(it.title)+'</div>';\n"
        "          html+='<div class=\"story-time\">'+timeAgo(it.date)+'</div>';\n"
        "          html+='</div></div></div>';\n"
        "        }\n"
        "        html+='</div>';\n"  # close stories-grid
        "      }\n"
        "      html+='</div>';\n"
        "    });\n"
        "\n"
        "    carousel.innerHTML=html;\n"
        "\n"
        "    /* Use event delegation instead of per-card listeners */\n"
        "    carousel.onclick=function(e){\n"
        "      var card=e.target.closest('.hero-card,.story-card');\n"
        "      if(!card)return;\n"
        "      e.preventDefault();\n"
        "      var id=card.getAttribute('data-id');\n"
        "      var item=itemDataMap[id];\n"
        "      if(item)expandCard(item);\n"
        "    };\n"
        "\n"
        "    buildDots();\n"
        "    if(!scrollObserverBound)initScrollObserver();\n"
        "  }\n"
        "\n"
        "  /* Expand / collapse card */\n"
        "  function expandCard(item){\n"
        "    var html='';\n"
        "    if(item.img)html+='<img class=\"expand-img\" src=\"'+proxyImg(item.img)+'\" alt=\"\" onerror=\"this.style.display=\\'none\\'\"/>';\n"
        "    html+='<div class=\"expand-body\">';\n"
        "    html+='<div class=\"expand-source\" style=\"color:#FFD233\">'+esc(item.source)+'</div>';\n"
        "    html+='<div class=\"expand-title\">'+esc(item.title)+'</div>';\n"
        "    html+='<div class=\"expand-time\">'+timeAgo(item.date)+'</div>';\n"
        "    if(item.desc)html+='<div class=\"expand-desc\">'+esc(item.desc)+'</div>';\n"
        "    if(item.link)html+='<a class=\"expand-link\" href=\"'+esc(item.link)+'\" target=\"_blank\" rel=\"noopener\">Read full story \\u2197</a>';\n"
        "    html+='</div>';\n"
        "    document.getElementById('expand-content').innerHTML=html;\n"
        "    document.getElementById('expand-backdrop').classList.add('open');\n"
        "    document.getElementById('expand-panel').classList.add('open');\n"
        "  }\n"
        "  function collapseCard(){\n"
        "    document.getElementById('expand-backdrop').classList.remove('open');\n"
        "    document.getElementById('expand-panel').classList.remove('open');\n"
        "  }\n"
        "  document.getElementById('expand-backdrop').addEventListener('click',collapseCard);\n"
        "  (function(){\n"
        "    var panel=document.getElementById('expand-panel');\n"
        "    var sy=0,dragging=false;\n"
        "    panel.addEventListener('touchstart',function(e){if(panel.scrollTop<=0){sy=e.touches[0].clientY;dragging=true;}},{passive:true});\n"
        "    panel.addEventListener('touchmove',function(e){if(!dragging)return;var dy=e.touches[0].clientY-sy;if(dy>0){panel.style.transform='translateY('+dy+'px)';panel.style.transition='none';}},{passive:true});\n"
        "    panel.addEventListener('touchend',function(){if(!dragging)return;dragging=false;panel.style.transition='transform .4s cubic-bezier(.4,0,.2,1)';var dy=parseInt(panel.style.transform.replace(/[^0-9-]/g,'')||'0',10);if(dy>80)collapseCard();else panel.style.transform=panel.classList.contains('open')?'translateY(0)':'translateY(100%)';},{passive:true});\n"
        "  })();\n"
        "\n"
        "  /* Fetch news */\n"
        "  function loadNews(){\n"
        "    var indEl=document.getElementById('refresh-ind');\n"
        "    if(indEl){indEl.style.opacity='1';indEl.style.animation='spin .6s linear infinite';}\n"
        "    fetch('/api/news/feed',{signal:AbortSignal.timeout(12000)})\n"
        "      .then(function(r){return r.json();})\n"
        "      .then(function(data){\n"
        "        allItems=[];\n"
        "        if(data.items&&data.items.length){\n"
        "          data.items.forEach(function(it){\n"
        "            allItems.push({\n"
        "              title:it.title||'',link:it.link||'',desc:it.description||'',\n"
        "              date:it.pubDate?new Date(it.pubDate):new Date(),\n"
        "              img:it.image||'',source:it.source||'Unknown',\n"
        "              category:it.category||'tech'\n"
        "            });\n"
        "          });\n"
        "        }\n"
        "        render();\n"
        "        if(indEl){indEl.style.animation='breathe 3s ease infinite';}\n"
        "      })\n"
        "      .catch(function(err){\n"
        "        console.error('[PearlOS News]',err);\n"
        "        if(indEl){indEl.style.animation='breathe 3s ease infinite';}\n"
        "      });\n"
        "  }\n"
        "\n"
        "  /* Pull-to-refresh on active column */\n"
        "  (function(){\n"
        "    var ptrEl=document.getElementById('ptr-indicator');\n"
        "    var startY=0,pulling=false,triggered=false;\n"
        "    document.addEventListener('touchstart',function(e){\n"
        "      var col=document.querySelector('.cat-column');\n"
        "      if(col&&col.scrollTop<=0){startY=e.touches[0].clientY;pulling=true;triggered=false;}\n"
        "    },{passive:true});\n"
        "    document.addEventListener('touchmove',function(e){\n"
        "      if(!pulling)return;var dy=e.touches[0].clientY-startY;\n"
        "      if(dy>0&&dy<120){ptrEl.style.opacity=String(Math.min(dy/80,1));ptrEl.style.transform='translateY('+(dy*.4-15)+'px)';}\n"
        "      if(dy>80&&!triggered)triggered=true;\n"
        "    },{passive:true});\n"
        "    document.addEventListener('touchend',function(){pulling=false;ptrEl.style.opacity='0';ptrEl.style.transform='translateY(-15px)';if(triggered)loadNews();},{passive:true});\n"
        "  })();\n"
        "\n"
        "  /* Pearl postMessage control */\n"
        "  window.addEventListener('message',function(e){\n"
        "    if(!e.data||e.data.type!=='news-navigate')return;\n"
        "    if(e.data.category){scrollToCategory(e.data.category);return;}\n"
        "    if(e.data.direction==='left'){scrollToIndex(currentIndex-1);}\n"
        "    else if(e.data.direction==='right'){scrollToIndex(currentIndex+1);}\n"
        "  });\n"
        "\n"
        "  /* Settings */\n"
        "  document.getElementById('btn-settings').addEventListener('click',function(){\n"
        "    document.getElementById('settings-overlay').classList.add('open');\n"
        "    loadSettingsUI();\n"
        "  });\n"
        "  window.closeSettings=function(){document.getElementById('settings-overlay').classList.remove('open');loadNews();};\n"
        "  function loadSettingsUI(){\n"
        "    fetch('/api/news/config').then(function(r){return r.json();}).then(function(cfg){renderFeedList(cfg.feeds||[]);}).catch(function(){renderFeedList([]);});\n"
        "  }\n"
        "  function renderFeedList(feeds){\n"
        "    var el=document.getElementById('feed-list');\n"
        "    if(!feeds.length){el.innerHTML='<div style=\"text-align:center;padding:16px;color:rgba(250,248,245,.4);font-size:13px;\">No feeds configured</div>';return;}\n"
        "    el.innerHTML=feeds.map(function(f){\n"
        "      return '<div class=\"feed-item\"><div class=\"feed-toggle'+(f.enabled?' on':'')+'\" onclick=\"toggleFeed(\\''+esc(f.url)+'\\')\"><div class=\"knob\"></div></div><div style=\"flex:1;min-width:0;\"><div class=\"feed-name\">'+esc(f.name)+'</div><div class=\"feed-url\">'+esc(f.url)+'</div></div><button class=\"feed-remove\" onclick=\"removeFeed(\\''+esc(f.url)+'\\')\">\u2715</button></div>';\n"
        "    }).join('');\n"
        "  }\n"
        "  window.toggleFeed=function(url){fetch('/api/news/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'toggle',feed:{url:url}})}).then(function(r){return r.json();}).then(function(cfg){renderFeedList(cfg.feeds||[]);});};\n"
        "  window.removeFeed=function(url){fetch('/api/news/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove',feed:{url:url}})}).then(function(r){return r.json();}).then(function(cfg){renderFeedList(cfg.feeds||[]);});};\n"
        "  window.addFeed=function(){var inp=document.getElementById('add-url');var url=inp.value.trim();if(!url)return;var name='Custom';try{name=new URL(url).hostname.replace('www.','').replace('feeds.','').split('.')[0];name=name.charAt(0).toUpperCase()+name.slice(1);}catch(e){}fetch('/api/news/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'add',feed:{url:url,name:name,enabled:true}})}).then(function(r){return r.json();}).then(function(cfg){renderFeedList(cfg.feeds||[]);inp.value='';});};\n"
        "  window.resetFeeds=function(){fetch('/api/news/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reset'})}).then(function(r){return r.json();}).then(function(cfg){renderFeedList(cfg.feeds||[]);});};\n"
        "  document.getElementById('settings-overlay').addEventListener('click',function(e){if(e.target===this)closeSettings();});\n"
        "\n"
        "  /* Button handlers */\n"
        "  document.getElementById('btn-refresh').addEventListener('click',function(){loadNews();});\n"
        "\n"
        "  /* Category name aliases */\n"
        "  var CATEGORY_ALIASES={technology:'tech',ent:'entertainment',sci:'science',pol:'politics',biz:'business'};\n"
        "  function normalizeCategoryName(name){\n"
        "    if(!name)return null;\n"
        "    var n=name.toLowerCase().trim();\n"
        "    return CATEGORY_ALIASES[n]||n;\n"
        "  }\n"
        "\n"
        "  /* Init */\n"
        "  var INITIAL_CATEGORY=" + (f"normalizeCategoryName('{initial_category}')" if initial_category else "null") + ";\n"
        "  var origRender=render;\n"
        "  var firstRender=true;\n"
        "  render=function(){\n"
        "    origRender();\n"
        "    if(firstRender&&INITIAL_CATEGORY){\n"
        "      firstRender=false;\n"
        "      /* Wait for layout + scroll-snap to settle */\n"
        "      requestAnimationFrame(function(){\n"
        "        requestAnimationFrame(function(){\n"
        "          setTimeout(function(){scrollToCategory(INITIAL_CATEGORY);},50);\n"
        "        });\n"
        "      });\n"
        "    }\n"
        "  };\n"
        "  loadNews();\n"
        "  var refreshTimer=setInterval(loadNews,300000);\n"
        "})();\n"
        '</script>\n'
        '</div>\n'
        '</body></html>'
    )
