name: deploy-mesh-pearl

on:
  release:
    types: [published]
  workflow_dispatch:  # <-- manual trigger
jobs:
  mesh:
    uses: ./.github/workflows/deploy-app.yml
    with:
      app_name: mesh
      dockerfile_path: apps/mesh/Dockerfile
      environment: pearl
    permissions:
      id-token: write    # obtain OIDC token
      contents: read
    secrets:
      SUBMODULE_PAT: ${{ secrets.NIAXP_PAT }}
